# -*- coding: utf-8 -*-
"""Questão 7 - lista5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWyHJRvR8C55yj3zJVlDpBcBibSTnGiH

Questão 7a)
"""

def altamente_compostos(n):
  """
  Função que, tendo como entrada um inteiro positivo n, 
  retorna a lista de todos os números altamente compostos 
  menores ou iguais a n.
  """
  lista_div = []
  lista_num_alt_comp = []
  for num_testado in range(1,n+1):
      conta_div = 1
      for num_teste_div in range(2,num_testado+1):
          if num_testado % num_teste_div == 0:
                conta_div += 1
      lista_div.append(conta_div)
      if len(lista_div) == 1:
          lista_num_alt_comp.append(num_testado)
      elif max(lista_div[:-1]) < lista_div[-1]:
          lista_num_alt_comp.append(num_testado)
  return lista_num_alt_comp

"""Questão 7b)"""

len(altamente_compostos(5000))

altamente_compostos(5000)